# Docker Compose YAML file for lighttpd

# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

version: "3.0"
services:
  lighttpd:
    build: .
    image: docker-lighttpd:latest
    container_name: lighttpd
    hostname: lighttpd
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/htdocs:/var/www/localhost/htdocs
      - ./data/certs:/var/www/localhost/certs
      - ./data/vhosts/vhost1:/var/www/localhost/vhost1
      - ./data/vhosts/vhost2:/var/www/localhost/vhost2
      - ./data/config:/etc/lighttpd
    restart: unless-stopped
    tty: true
