# Docker Compose YAML file for lighttpd

# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

version: "3.0"
services:
  lighttpd:
    build: .
    image: anoikisnomads/lighttpd:latest
    container_name: lighttpd
    hostname: lighttpd
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/config:/etc/lighttpd # lighttpd configs, including vhosts and mods
      - ./data/certs:/var/www/certs # place SSL certificates here
      - ./data/htdocs:/var/www/htdocs # htdocs for the default host
      - ./data/vhosts/vhost1:/var/www/vhost1 # example folder for virtual host
      - ./data/vhosts/vhost2:/var/www/vhost2 # example folder for virtual host
    restart: unless-stopped
    tty: true
